x=input("Enter your name: ")
y=int(input("Enter your age: "))
z=float(input("Enter your height in m: "))
print(type(x))
print(type(y))
print(type(z))
a=str(y)
h=str(z*100)
print(x," is "+a+" years old")
print("Height in cm is "+h)